name: ${project.name}
main: com.volmit.fulcrum.Fulcrum
version: ${project.version}
load: startup
content:
  sounds:
    material-hardwood:
      volume: 0.8f
      pitch: 1f
      subtitle: 'Hard Wood'
      resources: 
      - 'wood/wood_walk<1-11>'
      - 'wood/deckwood_run3'
    material-hardwood-step: 
      copy: material-hardwood
      volume: 0.3f
      pitch: 1.2f
  items: 
    metal-plate:
      name: 'Metal Plate'
      enchanted: false
      stack-size: 64
  blocks:
    hard-wood: 
      render-mode: PEDISTAL
      name: 'Hard Wood'
      enchanted: false
      stack-size: 64
      sounds: 
        break: material-hardwood
        place: material-hardwood
        step: material-hardwood-step
  inventories:
    smeltery:
      enchanted: false
commands:
  fulcrum:
    aliases: [fu, fulc, fm]
  scm:
    aliases: [mbscm]